set(command "/usr/local/bin/cmake;-P;/home/svemula/waffle_test/waffleClient/cmakebuild/openssl_ep-prefix/src/openssl_ep-stamp/download-openssl_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/bin/cmake;-P;/home/svemula/waffle_test/waffleClient/cmakebuild/openssl_ep-prefix/src/openssl_ep-stamp/verify-openssl_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/local/bin/cmake;-P;/home/svemula/waffle_test/waffleClient/cmakebuild/openssl_ep-prefix/src/openssl_ep-stamp/extract-openssl_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
