set(command "/opt/homebrew/Cellar/cmake/3.23.1_1/bin/cmake;-P;/Users/svemula/Desktop/Downloads/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep-stamp/download-thrift_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/opt/homebrew/Cellar/cmake/3.23.1_1/bin/cmake;-P;/Users/svemula/Desktop/Downloads/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep-stamp/verify-thrift_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/opt/homebrew/Cellar/cmake/3.23.1_1/bin/cmake;-P;/Users/svemula/Desktop/Downloads/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep-stamp/extract-thrift_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
