
cmake_minimum_required(VERSION 3.15)

set(command "/usr/local/bin/cmake;-Wno-dev;-DCMAKE_CXX_COMPILER=/usr/bin/c++;-DCMAKE_C_COMPILER=/usr/bin/cc;-DCMAKE_BUILD_TYPE=;-DCMAKE_INSTALL_PREFIX=/home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/external/thrift_ep;-DCMAKE_INSTALL_RPATH=/home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/external/thrift_ep/lib;-DBUILD_COMPILER=;-DBUILD_TESTING=OFF;-DWITH_SHARED_LIB=OFF;-DWITH_QT4=OFF;-DWITH_QT5=OFF;-DWITH_C_GLIB=OFF;-DWITH_HASKELL=OFF;-DWITH_LIBEVENT=ON;-DWITH_ZLIB=OFF;-DWITH_JAVA=OFF;-DWITH_PYTHON=OFF;-DWITH_CPP=ON;-DWITH_STDTHREADS=OFF;-DWITH_BOOSTTHREADS=OFF;-DWITH_STATIC_LIB=ON;-DCMAKE_PREFIX_PATH=\;/home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/external/boost_ep\;/home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/external/libevent_ep;-GUnix Makefiles;-S;/home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep;-B;/home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep-build")
set(log_merged "")
set(log_output_on_failure "")
set(stdout_log "/home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-configure-out.log")
set(stderr_log "/home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-configure-err.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
)
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  /home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-configure-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  if(NOT "Unix Makefiles" MATCHES "Ninja")
    set(msg "thrift_ep configure command succeeded.  See also /home/svemula/Waffle/waffle_test/waffleClient/cmakebuild/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-configure-*.log")
    message(STATUS "${msg}")
  endif()
endif()
